// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// flowCalcCpp
arma::mat flowCalcCpp(const arma::mat Am, const arma::mat Cm);
RcppExport SEXP _FLCNA_flowCalcCpp(SEXP AmSEXP, SEXP CmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type Am(AmSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Cm(CmSEXP);
    rcpp_result_gen = Rcpp::wrap(flowCalcCpp(Am, Cm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FLCNA_flowCalcCpp", (DL_FUNC) &_FLCNA_flowCalcCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_FLCNA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
