# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix calculation in RcppArmadillo.
#'
#' @param Am matrix
#' @param Cm matrix
#' @return Matrix, that is \code{inv(Am)%*%Cm}
flowCalcCpp <- function(Am, Cm) {
    .Call('_FLCNA_flowCalcCpp_I', PACKAGE = 'FLCNA', Am, Cm)
}

